// Copyright (c) 2026 Hemashushu <hippospark@gmail.com>, All rights reserved.
//
// This Source Code Form is subject to the terms of
// the Mozilla Public License version 2.0 and additional exceptions.
// For more details, see the LICENSE, LICENSE.additional, and CONTRIBUTING files.

use std::collections::HashMap;

use crate::{
    error::LinkerError,
    macho::module::{RelocatableModule, Symbol, SymbolBind},
};

/// Filter out modules that are not reachable from the main module.
///
/// The first module (`modules[0]`) is the main module containing the entry point.
/// This function traverses external symbol references to find all reachable modules.
pub fn filter<'a>(
    modules: Vec<RelocatableModule<'a>>,
    ignore_external_symbol_names: &[String],
) -> Result<Vec<RelocatableModule<'a>>, LinkerError> {
    let add_symbol_to_map = |map: &mut HashMap<String, (usize, bool)>,
                             name: &str,
                             bind: &SymbolBind,
                             module_index: usize,
                             module_name: &str|
     -> Result<(), LinkerError> {
        match bind {
            SymbolBind::Global => {
                if let Some((existing_module_index, existing_is_weak)) = map.get(name)
                    && !*existing_is_weak
                {
                    return Err(LinkerError::Message(format!(
                        "Duplicate strong symbol \"{}\" defined in module \"{}\" and module \"{}\"",
                        name, modules[*existing_module_index].name, module_name
                    )));
                }
                map.insert(name.to_string(), (module_index, false));
            }
            SymbolBind::Weak if !map.contains_key(name) => {
                map.insert(name.to_string(), (module_index, true));
            }
            _ => {}
        }
        Ok(())
    };

    let mut exported_symbols: HashMap<String, (usize, bool)> = HashMap::new();

    for (module_index, module) in modules.iter().enumerate() {
        for symbol in &module.symbols {
            match symbol {
                Symbol::Defined { name, bind, .. } | Symbol::Absolute { name, bind, .. } => {
                    add_symbol_to_map(
                        &mut exported_symbols,
                        name,
                        bind,
                        module_index,
                        &module.name,
                    )?;
                }
                _ => {}
            }
        }
    }

    let mut reachable_module_indices: Vec<usize> = vec![0];
    let mut pending_module_indices: Vec<usize> = vec![0];

    while let Some(module_index) = pending_module_indices.pop() {
        let module = &modules[module_index];
        for symbol in &module.symbols {
            if let Symbol::External(name) = symbol {
                if let Some((target_module_index, _)) = exported_symbols.get(name) {
                    if !reachable_module_indices.contains(target_module_index) {
                        reachable_module_indices.push(*target_module_index);
                        pending_module_indices.push(*target_module_index);
                    }
                } else if ignore_external_symbol_names.contains(name)
                    || is_system_dylib_symbol(name)
                {
                    // Symbol generated by the linker or provided by system libraries
                } else {
                    return Err(LinkerError::Message(format!(
                        "Unresolved external symbol \"{}\" in module \"{}\"",
                        name, module.name
                    )));
                }
            }
        }
    }

    let reachable_modules = modules
        .into_iter()
        .enumerate()
        .filter_map(|(index, module)| {
            if reachable_module_indices.contains(&index) {
                Some(module)
            } else {
                None
            }
        })
        .collect::<Vec<_>>();

    Ok(reachable_modules)
}

fn is_system_dylib_symbol(name: &str) -> bool {
    matches!(
        name,
        "_printf" | "_puts" | "_fputs" | "___stdoutp" | "_write" | "_exit" | "_malloc" | "_free" | "_strlen" | "_memset" | "_memcpy"
    )
}
